# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfoodpref_usermatchpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
