# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160529_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermatchpref',
            old_name='is_alcohol',
            new_name='match_alcohol',
        ),
        migrations.RenameField(
            model_name='usermatchpref',
            old_name='is_diabetic',
            new_name='match_diabetic',
        ),
        migrations.RenameField(
            model_name='usermatchpref',
            old_name='is_gluten',
            new_name='match_gluten',
        ),
        migrations.RenameField(
            model_name='usermatchpref',
            old_name='is_kosher',
            new_name='match_kosher',
        ),
        migrations.RenameField(
            model_name='usermatchpref',
            old_name='is_lactose',
            new_name='match_lactose',
        ),
        migrations.RenameField(
            model_name='usermatchpref',
            old_name='is_peanut',
            new_name='match_peanut',
        ),
        migrations.RenameField(
            model_name='usermatchpref',
            old_name='is_vegan',
            new_name='match_vegan',
        ),
        migrations.RenameField(
            model_name='usermatchpref',
            old_name='is_vegetarian',
            new_name='match_vegetarian',
        ),
    ]
