# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160530_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
