# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
